services:
  app:
    image: vuanem-ns:latest
    build:
      context: .
      args:
        PYTHON_DEV: dev
    container_name: vuanem-ns
    volumes:
      - ./creds/${CREDS_FILENAME}.json:/tmp/${CREDS_FILENAME}.json
      - ./data:/app/data
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/${CREDS_FILENAME}.json
      K_SERVICE: dev
      K_CONFIGURATION: dev
      K_REVISION: dev-00001
      PROJECT_ID: ${PROJECT_ID}
      TOPIC_ID: ${TOPIC_ID}
      ACCOUNT_ID: ${ACCOUNT_ID}
      ROLE_ID: ${ROLE_ID}
      NS_UID: ${NS_UID}
      NS_PWD: ${NS_PWD}
      ROLE_ID2: ${ROLE_ID2}
      NS_UID2: ${NS_UID2}
      NS_PWD2: ${NS_PWD2}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      PG_HOST: ${PG_HOST}
      PG_DB: ${PG_DB}
      PG_UID: ${PG_UID}
      PG_PWD: ${PG_PWD}

    ports:
      - '8080:8080'
    user: '0'
