services:
  app:
    image: vuanem-suiteanalytics-connect:latest
    build:
      context: .
      args:
        BUILD_ENV: dev
    container_name: vuanem-suiteanalytics-connect
    volumes:
      - ./${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/{GOOGLE_APPLICATION_CREDENTIALS}
      - ./data:/app/data
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/{GOOGLE_APPLICATION_CREDENTIALS}
      K_SERVICE: dev
      K_CONFIGURATION: dev
      K_REVISION: dev-00001
      
      ROLE_ID: ${ROLE_ID}
      NS_UID: ${NS_UID}
      NS_PWD: ${NS_PWD}

      ROLE_ID2: ${ROLE_ID2}
      NS_UID2: ${NS_UID2}
      NS_PWD2: ${NS_PWD2}
      
      PUBLIC_URL: ${PUBLIC_URL}
      GCP_SA: ${GCP_SA}
    ports:
      - '8080:8080'
    user: '0'
