SELECT 
	DATE_CREATED,
	DELIVERY_PERSON_EXTID,
	DELIVERY_PERSON_ID,
	DELIVERY_PERSON_NAME,
	IS_INACTIVE,
	LAST_MODIFIED_DATE,
	REF__EMPLOYEE_ID,
	VN_CODE
FROM "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".DELIVERY_PERSON
