SELECT
	DATE_LAST_MODIFIED,
	DEPARTMENT_DESCRIPTION,
	DEPARTMENT_EXTID,
	DEPARTMENT_ID,
	FULL_NAME,
	ISINACTIVE,
	IS_INCLUDING_CHILD_SUBS,
	NAME,
	PARENT_ID
FROM
	"Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".DEPARTMENTS
