SELECT
    CLASSES.CLASS_ID,
    CLASSES.DATE_LAST_MODIFIED,
    CLASSES.FULL_NAME,
    CLASSES.ISINACTIVE,
    CLASSES.CLASS_DESCRIPTION,
    CLASSES.NAME,
    CLASSES.PRODUCT_GROUP_CODE
FROM
    "Vua Nem Joint Stock Company".Administrator.CLASSES CLASSES
