SELECT
        LOCATIONS.LOCATION_ID,
        LOCATIONS.STORE_NAME,
        LOCATIONS.CURRENT_ASM,
        TIMESTAMP_TRUNC(TRANDATE, MONTH) AS START_OF_MONTH,
        - SUM(TRANSACTION_LINES.NET_AMOUNT) AS SO,
        - SUM(TRANSACTION_LINES.ITEM_COUNT) AS QTY_SO
FROM
        NetSuite._stage_TRANSACTIONS AS TRANSACTIONS
        LEFT JOIN NetSuite._stage_TRANSACTION_LINES AS TRANSACTION_LINES ON TRANSACTION_LINES.TRANSACTION_ID = TRANSACTIONS.TRANSACTION_ID
        LEFT JOIN NetSuite._stage_LOCATIONS AS LOCATIONS ON LOCATIONS.LOCATION_ID = TRANSACTIONS.LOCATION_ID
WHERE
        TRANSACTION_LINES.ACCOUNT_ID IN (
                480,
                482,
                487,
                498,
                505,
                508,
                509,
                510,
                511,
                54,
                1079,
                1170
        )
        AND TRANSACTIONS.TRANSACTION_TYPE IN ('Sales Order')
        AND TRANSACTIONS.STATUS <> 'Closed'
GROUP BY
        LOCATIONS.LOCATION_ID,
        LOCATIONS.STORE_NAME,
        LOCATIONS.CURRENT_ASM,
        START_OF_MONTH
