from netsuite.pipeline.interface import Pipeline, Key
from netsuite.repo import netsuite_connection
from db.bigquery import timeframe_builder, update

pipeline = Pipeline(
    "CUSTOMERS",
    [
        {"name": "CUSTOMER_ID", "type": "INTEGER"},
        {"name": "PHONE", "type": "STRING"},
        {"name": "EMAIL", "type": "STRING"},
        {"name": "CATEGORY_0", "type": "STRING"},
        {"name": "FULL_NAME", "type": "STRING"},
        {"name": "FIRSTNAME", "type": "STRING"},
        {"name": "MIDDLENAME", "type": "STRING"},
        {"name": "LASTNAME", "type": "STRING"},
        {"name": "NAME", "type": "STRING"},
        {"name": "BILLADDRESS", "type": "STRING"},
        {"name": "SHIPADDRESS", "type": "STRING"},
        {"name": "CITY", "type": "STRING"},
        {"name": "COMPANYNAME", "type": "STRING"},
        {"name": "CONVERTED_TO_ID", "type": "INTEGER"},
        {"name": "COUNTRY", "type": "STRING"},
        {"name": "CREATE_DATE", "type": "TIMESTAMP"},
        {"name": "DATE_CLOSED", "type": "TIMESTAMP"},
        {"name": "DATE_CONVSERSION", "type": "TIMESTAMP"},
        {"name": "DATE_FIRST_ORDER", "type": "TIMESTAMP"},
        {"name": "DATE_FIRST_SALE", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_MODIFIED", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_ORDER", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_SALE", "type": "TIMESTAMP"},
        {"name": "DATE_LEAD", "type": "TIMESTAMP"},
        {"name": "DATE_PROSPECT", "type": "TIMESTAMP"},
        {"name": "FROM_CAMPAIGN", "type": "STRING"},
        {"name": "FROM_LANDING", "type": "STRING"},
        {"name": "HOME_PHONE", "type": "STRING"},
        {"name": "ISINACTIVE", "type": "STRING"},
        {"name": "LAST_MODIFIED_DATE", "type": "TIMESTAMP"},
        {"name": "LEAD_SOURCE_ID", "type": "INTEGER"},
        {"name": "SMS_PROMO_ID", "type": "STRING"},
        {"name": "SOURCES_ID", "type": "INTEGER"},
        {"name": "STATUS", "type": "STRING"},
        {"name": "SUBSIDIARY_ID", "type": "INTEGER"},
        {"name": "DATE_OF_BIRTH", "type": "TIMESTAMP"},
        {"name": "LOYALTY_GROUP_ID", "type": "INTEGER"},
    ],
    conn_fn=netsuite_connection,
    query_fn=lambda tr: f"""
        SELECT
            CUSTOMER_ID,
            PHONE,
            EMAIL,
            CATEGORY_0,
            FULL_NAME,
            FIRSTNAME,
            MIDDLENAME,
            LASTNAME,
            NAME,
            BILLADDRESS,
            SHIPADDRESS,
            CITY,
            COMPANYNAME,
            CONVERTED_TO_ID,
            COUNTRY,
            CREATE_DATE,
            DATE_CLOSED,
            DATE_CONVSERSION,
            DATE_FIRST_ORDER,
            DATE_FIRST_SALE,
            DATE_LAST_MODIFIED,
            DATE_LAST_ORDER,
            DATE_LAST_SALE,
            DATE_LEAD,
            DATE_PROSPECT,
            FROM_CAMPAIGN,
            FROM_LANDING,
            HOME_PHONE,
            ISINACTIVE,
            LAST_MODIFIED_DATE,
            LEAD_SOURCE_ID,
            SMS_PROMO_ID,
            SOURCES_ID,
            STATUS,
            SUBSIDIARY_ID,
            DATE_OF_BIRTH,
            LOYALTY_GROUP_ID
        FROM
            "Vua Nem Joint Stock Company".Administrator.CUSTOMERS
        WHERE
            DATE_LAST_MODIFIED >= '{tr[0]}'
            AND DATE_LAST_MODIFIED <= '{tr[1]}'
    """,
    param_fn=timeframe_builder,
    key=Key(
        id_key=["CUSTOMER_ID"],
        cursor_key=["DATE_LAST_MODIFIED"],
    ),
    load_callback_fn=update,
)
