from netsuite.pipeline.interface import Pipeline, Key
from netsuite.repo import netsuite_connection
from db.bigquery import timeframe_builder, update

pipeline = Pipeline(
    "TRANSACTIONS",
    [
        {"name": "TRANID", "type": "STRING"},
        {"name": "TRANSACTION_ID", "type": "INTEGER"},
        {"name": "TRANSACTION_NUMBER", "type": "STRING"},
        {"name": "TRANDATE", "type": "TIMESTAMP"},
        {"name": "BILLADDRESS", "type": "STRING"},
        {"name": "CLOSED", "type": "TIMESTAMP"},
        {"name": "CLOSED_REASON_ID", "type": "INTEGER"},
        {"name": "CREATE_DATE", "type": "TIMESTAMP"},
        {"name": "CREATED_FROM_ID", "type": "INTEGER"},
        {"name": "CUSTOMER_PHONE", "type": "STRING"},
        {"name": "DATE_LAST_MODIFIED", "type": "TIMESTAMP"},
        {"name": "DELIVERY_PERSON_ID", "type": "INTEGER"},
        {"name": "DELIVERY_STATUS_ID", "type": "INTEGER"},
        {"name": "DELIVERY_TERMS_ID", "type": "INTEGER"},
        {"name": "DELIVERY_VEHICLE_ID", "type": "INTEGER"},
        {"name": "DEPOSIT_PAYMENT_METHOD_ID", "type": "INTEGER"},
        {"name": "EINVOICE_STATUS", "type": "STRING"},
        {"name": "EMAIL", "type": "STRING"},
        {"name": "ENTITY_ID", "type": "INTEGER"},
        {"name": "EVENT_ID", "type": "INTEGER"},
        {"name": "EXPECTED_DELIVERY_DATE_C", "type": "TIMESTAMP"},
        {"name": "IN_CHARGE_LOCATION_ID", "type": "INTEGER"},
        {"name": "KHNG_YU_CU_T_CC", "type": "STRING"},
        {"name": "LEAD_SOURCE_ID", "type": "INTEGER"},
        {"name": "LICENSE_PLATE", "type": "STRING"},
        {"name": "LICENSE_PLATE_V_2_ID", "type": "INTEGER"},
        {"name": "LOCATION_ID", "type": "INTEGER"},
        {"name": "LOYALTY_CUSTOMER_GROUP_ID", "type": "INTEGER"},
        {"name": "LOYALTY_ELIGIBILITY", "type": "STRING"},
        {"name": "LOYALTY_LOCATION_GROUP_ID", "type": "INTEGER"},
        {"name": "MAGENTO_ORDER_NUMBER", "type": "STRING"},
        {"name": "MAGENTO_SO_ID", "type": "STRING"},
        {"name": "MAGENTO_TOTAL", "type": "INTEGER"},
        {"name": "MEMO", "type": "STRING"},
        {"name": "ORDER_PAYMENT_METHOD_ID", "type": "INTEGER"},
        {"name": "PARTNER_ID", "type": "INTEGER"},
        {"name": "PROMOTION_CODE_ID", "type": "STRING"},
        {"name": "RECIPIENT", "type": "STRING"},
        {"name": "RECIPIENT_PHONE", "type": "STRING"},
        {"name": "SALES_REP_ID", "type": "INTEGER"},
        {"name": "SHIPADDRESS", "type": "STRING"},
        {"name": "SHIPPING_METHOD_C_ID", "type": "INTEGER"},
        {"name": "STATUS", "type": "STRING"},
        {"name": "TRANSACTION_TYPE", "type": "STRING"},
        {"name": "REF__INVOICE__DELIVERY_ORDE_ID", "type": "INTEGER"},
        {"name": "REF__TRANSACTION_ID", "type": "INTEGER"},
        {"name": "RETURNED_REASON_ID", "type": "INTEGER"},
        {"name": "REFERENCE_SALES_ORDER_ID", "type": "INTEGER"},
        {"name": "TRANSFER_LOCATION", "type": "INTEGER"},
        {"name": "TRANSFER_ORDER_TYPE_ID", "type": "INTEGER"},
        {"name": "PURCHASE_ORDER_TYPE_ID", "type": "INTEGER"},
        {"name": "ONLINE_SUPPORT_REP_ID", "type": "INTEGER"},
        {"name": "SHIPMENT_RECEIVED", "type": "TIMESTAMP"},
        {"name": "REVENUE_COMMITMENT_STATUS", "type": "STRING"},
        {"name": "DUE_DATE", "type": "TIMESTAMP"},
        {"name": "CREATED_BY_ID", "type": "INTEGER"},
    ],
    conn_fn=netsuite_connection,
    query_fn=lambda tr: f"""
        SELECT
            TRANSACTION_ID,
            TRANSACTION_NUMBER,
            TRANDATE,
            TRANID,
            BILLADDRESS,
            CLOSED,
            CLOSED_REASON_ID,
            CREATE_DATE,
            CREATED_FROM_ID,
            CUSTOMER_PHONE,
            DATE_LAST_MODIFIED,
            DELIVERY_PERSON_ID,
            DELIVERY_STATUS_ID,
            DELIVERY_TERMS_ID,
            DELIVERY_VEHICLE_ID,
            DEPOSIT_PAYMENT_METHOD_ID,
            EINVOICE_GTGT_STATUS AS EINVOICE_STATUS,
            EMAIL,
            ENTITY_ID,
            EVENT_ID,
            EXPECTED_DELIVERY_DATE_C,
            IN_CHARGE_LOCATION_ID,
            KHNG_YU_CU_T_CC,
            LEAD_SOURCE_ID,
            LICENSE_PLATE,
            LICENSE_PLATE_V_2_ID,
            LOCATION_ID,
            LOYALTY_CUSTOMER_GROUP_ID,
            LOYALTY_ELIGIBILITY,
            LOYALTY_LOCATION_GROUP_ID,
            MAGENTO_ORDER_NUMBER,
            MAGENTO_SO_ID,
            MAGENTO_TOTAL,
            MEMO,
            ORDER_PAYMENT_METHOD_ID,
            PARTNER_ID,
            PROMOTION_CODE_ID,
            RECIPIENT,
            RECIPIENT_PHONE,
            SALES_REP_ID,
            SHIPADDRESS,
            SHIPPING_METHOD_C_ID,
            STATUS,
            TRANSACTION_TYPE,
            REF__INVOICE__DELIVERY_ORDE_ID,
            REF__TRANSACTION_ID,
            RETURNED_REASON_ID,
            REFERENCE_SALES_ORDER_ID,
            TRANSFER_LOCATION,
            TRANSFER_ORDER_TYPE_ID,
            PURCHASE_ORDER_TYPE_ID,
            ONLINE_SUPPORT_REP_ID,
            SHIPMENT_RECEIVED,
            REVENUE_COMMITMENT_STATUS,
            DUE_DATE,
            CREATED_BY_ID
        FROM
            "Vua Nem Joint Stock Company".Administrator.TRANSACTIONS
        WHERE
            TRANSACTIONS.DATE_LAST_MODIFIED >= '{tr[0]}'
            AND TRANSACTIONS.DATE_LAST_MODIFIED <= '{tr[1]}'
    """,
    param_fn=timeframe_builder,
    key=Key(
        id_key=["TRANSACTION_ID"],
        cursor_key=["DATE_LAST_MODIFIED"],
    ),
    load_callback_fn=update,
)
