from netsuite.pipeline.interface import Pipeline, Key
from netsuite.repo import netsuite_connection
from db.bigquery import timeframe_builder, update

pipeline = Pipeline(
    "TRANSACTIONS",
    [
        {"name": "TRANID", "type": "STRING"},
        {"name": "TRANSACTION_ID", "type": "INTEGER"},
        {"name": "TRANSACTION_NUMBER", "type": "STRING"},
        {"name": "TRANDATE", "type": "TIMESTAMP"},
        {"name": "BILLADDRESS", "type": "STRING"},
        {"name": "CLOSED", "type": "TIMESTAMP"},
        {"name": "CLOSED_REASON_ID", "type": "INTEGER"},
        {"name": "CREATE_DATE", "type": "TIMESTAMP"},
        {"name": "CREATED_FROM_ID", "type": "INTEGER"},
        {"name": "CUSTOMER_PHONE", "type": "STRING"},
        {"name": "DATE_LAST_MODIFIED", "type": "TIMESTAMP"},
        {"name": "DELIVERY_PERSON_ID", "type": "INTEGER"},
        {"name": "DELIVERY_STATUS_ID", "type": "INTEGER"},
        {"name": "DELIVERY_TERMS_ID", "type": "INTEGER"},
        {"name": "DELIVERY_VEHICLE_ID", "type": "INTEGER"},
        {"name": "DEPOSIT_PAYMENT_METHOD_ID", "type": "INTEGER"},
        {"name": "EINVOICE_STATUS", "type": "STRING"},
        {"name": "EMAIL", "type": "STRING"},
        {"name": "ENTITY_ID", "type": "INTEGER"},
        {"name": "EVENT_ID", "type": "INTEGER"},
        {"name": "EXPECTED_DELIVERY_DATE_C", "type": "TIMESTAMP"},
        {"name": "IN_CHARGE_LOCATION_ID", "type": "INTEGER"},
        {"name": "KHNG_YU_CU_T_CC", "type": "STRING"},
        {"name": "LEAD_SOURCE_ID", "type": "INTEGER"},
        {"name": "LICENSE_PLATE", "type": "STRING"},
        {"name": "LICENSE_PLATE_V_2_ID", "type": "INTEGER"},
        {"name": "LOCATION_ID", "type": "INTEGER"},
        {"name": "LOYALTY_CUSTOMER_GROUP_ID", "type": "INTEGER"},
        {"name": "LOYALTY_ELIGIBILITY", "type": "STRING"},
        {"name": "LOYALTY_LOCATION_GROUP_ID", "type": "INTEGER"},
        {"name": "MAGENTO_ORDER_NUMBER", "type": "STRING"},
        {"name": "MAGENTO_SO_ID", "type": "STRING"},
        {"name": "MAGENTO_TOTAL", "type": "INTEGER"},
        {"name": "MEMO", "type": "STRING"},
        {"name": "ORDER_PAYMENT_METHOD_ID", "type": "INTEGER"},
        {"name": "PARTNER_ID", "type": "INTEGER"},
        {"name": "PROMOTION_CODE_ID", "type": "STRING"},
        {"name": "RECIPIENT", "type": "STRING"},
        {"name": "RECIPIENT_PHONE", "type": "STRING"},
        {"name": "SALES_REP_ID", "type": "INTEGER"},
        {"name": "SHIPADDRESS", "type": "STRING"},
        {"name": "SHIPPING_METHOD_C_ID", "type": "INTEGER"},
        {"name": "STATUS", "type": "STRING"},
        {"name": "TRANSACTION_TYPE", "type": "STRING"},
        {"name": "REF__INVOICE__DELIVERY_ORDE_ID", "type": "INTEGER"},
        {"name": "REF__TRANSACTION_ID", "type": "INTEGER"},
        {"name": "RETURNED_REASON_ID", "type": "INTEGER"},
        {"name": "REFERENCE_SALES_ORDER_ID", "type": "INTEGER"},
        {"name": "TRANSFER_LOCATION", "type": "INTEGER"},
        {"name": "TRANSFER_ORDER_TYPE_ID", "type": "INTEGER"},
        {"name": "PURCHASE_ORDER_TYPE_ID", "type": "INTEGER"},
        {"name": "ONLINE_SUPPORT_REP_ID", "type": "INTEGER"},
    ],
    conn_fn=netsuite_connection,
    query_fn=lambda tr: f"""
        SELECT
            TRANSACTIONS.TRANSACTION_ID,
            TRANSACTIONS.TRANSACTION_NUMBER,
            TRANSACTIONS.TRANDATE,
            TRANSACTIONS.TRANID,
            TRANSACTIONS.BILLADDRESS,
            TRANSACTIONS.CLOSED,
            TRANSACTIONS.CLOSED_REASON_ID,
            TRANSACTIONS.CREATE_DATE,
            TRANSACTIONS.CREATED_FROM_ID,
            TRANSACTIONS.CUSTOMER_PHONE,
            TRANSACTIONS.DATE_LAST_MODIFIED,
            TRANSACTIONS.DELIVERY_PERSON_ID,
            TRANSACTIONS.DELIVERY_STATUS_ID,
            TRANSACTIONS.DELIVERY_TERMS_ID,
            TRANSACTIONS.DELIVERY_VEHICLE_ID,
            TRANSACTIONS.DEPOSIT_PAYMENT_METHOD_ID,
            -- TRANSACTIONS.EINVOICE_STATUS,
            NULL AS EINVOICE_STATUS,
            TRANSACTIONS.EMAIL,
            TRANSACTIONS.ENTITY_ID,
            TRANSACTIONS.EVENT_ID,
            TRANSACTIONS.EXPECTED_DELIVERY_DATE_C,
            TRANSACTIONS.IN_CHARGE_LOCATION_ID,
            TRANSACTIONS.KHNG_YU_CU_T_CC,
            TRANSACTIONS.LEAD_SOURCE_ID,
            TRANSACTIONS.LICENSE_PLATE,
            TRANSACTIONS.LICENSE_PLATE_V_2_ID,
            TRANSACTIONS.LOCATION_ID,
            TRANSACTIONS.LOYALTY_CUSTOMER_GROUP_ID,
            TRANSACTIONS.LOYALTY_ELIGIBILITY,
            TRANSACTIONS.LOYALTY_LOCATION_GROUP_ID,
            TRANSACTIONS.MAGENTO_ORDER_NUMBER,
            TRANSACTIONS.MAGENTO_SO_ID,
            TRANSACTIONS.MAGENTO_TOTAL,
            TRANSACTIONS.MEMO,
            TRANSACTIONS.ORDER_PAYMENT_METHOD_ID,
            TRANSACTIONS.PARTNER_ID,
            TRANSACTIONS.PROMOTION_CODE_ID,
            TRANSACTIONS.RECIPIENT,
            TRANSACTIONS.RECIPIENT_PHONE,
            TRANSACTIONS.SALES_REP_ID,
            TRANSACTIONS.SHIPADDRESS,
            TRANSACTIONS.SHIPPING_METHOD_C_ID,
            TRANSACTIONS.STATUS,
            TRANSACTIONS.TRANSACTION_TYPE,
            TRANSACTIONS.REF__INVOICE__DELIVERY_ORDE_ID,
            TRANSACTIONS.REF__TRANSACTION_ID,
            TRANSACTIONS.RETURNED_REASON_ID,
            TRANSACTIONS.REFERENCE_SALES_ORDER_ID,
            TRANSACTIONS.TRANSFER_LOCATION,
            TRANSACTIONS.TRANSFER_ORDER_TYPE_ID,
            TRANSACTIONS.PURCHASE_ORDER_TYPE_ID,
            TRANSACTIONS.ONLINE_SUPPORT_REP_ID
        FROM
            "Vua Nem Joint Stock Company".Administrator.TRANSACTIONS
        WHERE
            TRANSACTIONS.DATE_LAST_MODIFIED >= '{tr[0]}'
            AND TRANSACTIONS.DATE_LAST_MODIFIED <= '{tr[1]}'
    """,
    param_fn=timeframe_builder,
    key=Key(
        id_key=["TRANSACTION_ID"],
        rank_key=["TRANSACTION_ID"],
        cursor_key=["DATE_LAST_MODIFIED"],
        cursor_rank_key=["DATE_LAST_MODIFIED"],
        cursor_rn_key=["DATE_LAST_MODIFIED"],
    ),
    load_callback_fn=update,
)
