SELECT
	ACCOUNT_ID,
	DATE_LAST_MODIFIED,
	FULL_DESCRIPTION,
	DESCRIPTION,
	FULL_NAME,
	HEADER_0,
	SUBHEADER,
	LOCATION_ID,
	NAME,
	ACCOUNTNUMBER,
	TYPE_NAME
FROM
	"Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".ACCOUNTS
