SELECT 
	SUPPORT_INCIDENTS.ASSIGNED_ID,
	EMPLOYEES.NAME AS AGENT,
	SUPPORT_INCIDENTS.CASE_ID,
	SUPPORT_INCIDENTS.CASE_NUMBER,
	SUPPORT_INCIDENTS.CI_THIN AS CAI_THIEN,
	SUPPORT_INCIDENTS.CREATE_DATE,
	SUPPORT_INCIDENTS.L_DO_CHO_S_IM AS LY_DO_CHO_SO_DIEM,
	SUPPORT_INCIDENTS.L_DO_KHNG_MUA_HNG_ID AS LY_DO_KHONG_MUA_HANG,
	SUPPORT_INCIDENTS.NAME,
	CASE 
		WHEN SUPPORT_INCIDENTS.NV_BN_HNG_ID = '68378' THEN TRANSACTIONS.ONLINE_SUPPORT_REP_ID
		ELSE SUPPORT_INCIDENTS.NV_BN_HNG_ID
	END AS NVBH_ID,
	SUPPORT_INCIDENTS.NV_BO_HNH_M_ID AS BAOHANH_ID,	
	SUPPORT_INCIDENTS.NV_GIAO_HNG_ID AS NVGH_ID,
	SUPPORT_INCIDENTS.NV_H_TR_GIAO_HNG_ID AS HOTRO_ID,
	R2.LIST_ITEM_NAME AS RATING_Stage1_ttDigitalHotline,
	R1.LIST_ITEM_NAME AS RATING_Stage2_VaoCHkhongmua,
	R3.LIST_ITEM_NAME AS RATING_Stage5_SudungSP,
	R4.LIST_ITEM_NAME AS RATING_Stage4_Giaohang,
	R5.LIST_ITEM_NAME AS RATING_Stage3_SO,
	S1.LIST_ITEM_NAME AS SAO_NVBH,
	S2.LIST_ITEM_NAME AS SAO_NVGH,
	S3.LIST_ITEM_NAME AS SAO_BAOHANH,
	S4.LIST_ITEM_NAME AS SAO_HOTRO,
	SUPPORT_INCIDENTS.SO_LOCATION_ID,
	SUPPORT_INCIDENTS.SO_REFERENCE_ID,
	TRANSACTIONS.TRANID AS SO_ID,
	SUPPORT_INCIDENTS.NGY_HON_THNH_KHIU_NIBO_,
	CASETYPE.NAME as CASE_TYPE_NAME
FROM "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".SUPPORT_INCIDENTS
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".RATING AS NPS ON NPS.LIST_ID = SUPPORT_INCIDENTS.NPS_SCORE_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".CASETYPE ON 	CASETYPE.CASE_TYPE = SUPPORT_INCIDENTS.CASE_TYPE_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".RATING AS R1 ON R1.LIST_ID = SUPPORT_INCIDENTS.RATING_KHCH_VO_CH_CHA_MUA__ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".RATING AS R2 ON R2.LIST_ID = SUPPORT_INCIDENTS.RATING__KHCH_DIGITALHOTLINE_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".RATING AS R3 ON R3.LIST_ID = SUPPORT_INCIDENTS.RATING__SN_PHM_A_DNG_PHON_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".RATING AS R4 ON R4.LIST_ID = SUPPORT_INCIDENTS.RATING__SAU_KHI_GIAO_HNG_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".RATING AS R5 ON R5.LIST_ID = SUPPORT_INCIDENTS.RATING__SAU_KHI_LN_SO_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".RATING AS S1 ON S1.LIST_ID = SUPPORT_INCIDENTS.SAO_CHO_NVBH_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".RATING AS S2 ON S2.LIST_ID = SUPPORT_INCIDENTS.SAO_CHO_NVGH_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".RATING AS S3 ON S3.LIST_ID = SUPPORT_INCIDENTS.SAO_CHO_NV_BO_HNH_M_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".RATING AS S4 ON S4.LIST_ID = SUPPORT_INCIDENTS.SAO_CHO_NV_H_TR_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".EMPLOYEES ON EMPLOYEES.EMPLOYEE_ID = SUPPORT_INCIDENTS.ASSIGNED_ID
LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".TRANSACTIONS ON TRANSACTIONS.TRANSACTION_ID = SUPPORT_INCIDENTS.SO_REFERENCE_ID
WHERE
    SUPPORT_INCIDENTS.DATE_LAST_MODIFIED >= ?
