SELECT
    SUPPORT_INCIDENTS.ASSIGNED_ID,
    SUPPORT_INCIDENTS.CASE_ID,
    SUPPORT_INCIDENTS.CASE_NUMBER,
    SUPPORT_INCIDENTS.CASE_NUMBERCODE,
    SUPPORT_INCIDENTS.CASE_ORIGIN_ID,
    SUPPORT_INCIDENTS.CASE_PROFILE_ID,
    SUPPORT_INCIDENTS.CASE_TYPE_ID,
    SUPPORT_INCIDENTS.CI_THIN AS 'CAI_THIEN',
    SUPPORT_INCIDENTS.COMPANY_ID,
    SUPPORT_INCIDENTS.CREATE_DATE,
    SUPPORT_INCIDENTS.DATE_LAST_MODIFIED,
    SUPPORT_INCIDENTS.ISINACTIVE,
    SUPPORT_INCIDENTS.KIN_THC_T_VN_SP_ID AS 'KTTV',
    SUPPORT_INCIDENTS.L_DO_CHO_S_IM AS 'LY_DO_CHO_DIEM',
    SUPPORT_INCIDENTS.NAME,
    SUPPORT_INCIDENTS.NPS_SCORE_ID,
    SUPPORT_INCIDENTS.OWNER_ID,
    SUPPORT_INCIDENTS.PRIORITY,
    SUPPORT_INCIDENTS.SO_LOCATION_ID,
    SUPPORT_INCIDENTS.SO_REFERENCE_ID,
    SUPPORT_INCIDENTS.STAGE,
    SUPPORT_INCIDENTS.STATUS,
    CASE_TYPES.NAME AS TYPES_NAME,
    CASE_ORIGINS.NAME AS ORIGINS_NAME
FROM
    "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".SUPPORT_INCIDENTS
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".CASE_TYPES ON SUPPORT_INCIDENTS.CASE_TYPE_ID = CASE_TYPES.CASE_TYPE_ID
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".CASE_ORIGINS ON SUPPORT_INCIDENTS.CASE_ORIGIN_ID = CASE_ORIGINS.CASE_ORIGIN_ID
WHERE
    SUPPORT_INCIDENTS.DATE_LAST_MODIFIED >= ?
