SELECT
    TRANSACTIONS.TRANSACTION_ID,
    TRANSACTIONS.CREATE_DATE,
    TRANSACTION_LINES.LOCATION_ID,
    TRANSACTION_LINES.ITEM_ID,
    TRANSACTION_LINES.ITEM_COUNT,
    TRANSACTION_LINES.NET_AMOUNT
FROM
    (
        SELECT
            TRANSACTION_LINES.TRANSACTION_ID,
            TRANSACTION_LINES.LOCATION_ID,
            TRANSACTION_LINES.ITEM_ID,
            TRANSACTION_LINES.ITEM_COUNT,
            TRANSACTION_LINES.NET_AMOUNT
        FROM
            "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".TRANSACTION_LINES TRANSACTION_LINES
        WHERE
            TRANSACTION_LINES.ACCOUNT_ID IN (365, 366, 367, 370, 371)
    ) TRANSACTION_LINES
    INNER JOIN (
        SELECT
            TRANSACTIONS.TRANSACTION_ID,
            TRANSACTIONS.CREATE_DATE - 7 / 24 AS CREATE_DATE
        FROM
            "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".TRANSACTIONS TRANSACTIONS
        WHERE
            TRANSACTIONS.TRANSACTION_TYPE IN (
                'Credit Memo',
                'Invoice',
                'Item Fulfillment',
                'Inventory Adjustment',
                'Item Receipt'
            )
    ) TRANSACTIONS ON TRANSACTIONS.TRANSACTION_ID = TRANSACTION_LINES.TRANSACTION_ID
