SELECT
    ITEMS.ITEM_ID,
    ITEMS.CLASS_ID,
    ITEMS.FULL_NAME,
    ITEMS.DISPLAYNAME,
    ITEMS.NEW_ITEM_CODE,
    ITEMS.OLD_VN_CODE,
    ITEMS.VN__OLD_ITEM_CODE,
    ITEMS.PRODUCT_CODE,
    ITEMS.TYPE_NAME,
    ITEMS.SALESPRICE,
    ITEMS.SALESDESCRIPTION,
    INVENTORY_STATUS.LIST_ITEM_NAME AS 'STATUS',
    LIST__ITEM_COLOR.LIST_ITEM_NAME AS 'COLOR',
    LIST__ITEM_FEATURE.LIST_ITEM_NAME AS 'FEATURE',
    LIST__ITEM_MATERIAL.LIST_ITEM_NAME AS 'MATERIAL',
    SEGMENT_LIST.LIST_ITEM_NAME AS 'SEGMENT',
    LIST__MATTRESS_COMFORT_LEVELS.LIST_ITEM_NAME AS 'MATTRESS_COMFORT_LEVEL',
    PROMOTION_APPLIED_TO_VALUE.LIST_ITEM_NAME AS 'PROMOTION_APPLIED_TO',
    ITEMS.THICKNESS,
    ITEMS.THREADCOUNT,
    ITEMS.VENDOR_ID,
    ITEMS.WARRANTY,
    ITEMS.WEIGHT,
    ITEMS.KCH_THC_NG_GI,
    ITEMS.LENGTH_0,
    ITEMS.WIDTH,
    ITEMS.PROMOTION_START_DATE,
    ITEMS.PROMOTION_END_DATE,
    ITEMS.BUY_X_AMOUNT,
    ITEMS.BUY_X_ITEM_ID,
    ITEMS.BUY_X_QUANTITY,
    ITEMS.CREATED,
    ITEMS.DATE_LAST_MODIFIED,
    ITEMS.EXPENSE_ACCOUNT_ID,
    ITEMS.ISINACTIVE,
    ITEMS.ISONLINE,
    ITEMS.ITEM_EXTID,
    ITEMS.CODE_OF_SUPPLY_ID,
    ITEMS.LOYALTY_CATEGORY_ID
FROM
    "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".ITEMS
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".LIST__ITEM_COLOR ON LIST__ITEM_COLOR.LIST_ID = ITEMS.COLOR_ID
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".LIST__ITEM_FEATURE ON LIST__ITEM_FEATURE.LIST_ID = ITEMS.FEATURE_ID
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".INVENTORY_STATUS ON INVENTORY_STATUS.LIST_ID = ITEMS.ITEM_STATUS_ID
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".LIST__ITEM_MATERIAL ON LIST__ITEM_MATERIAL.LIST_ID = ITEMS.MATERIAL_ID
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".LIST__MATTRESS_COMFORT_LEVELS ON LIST__MATTRESS_COMFORT_LEVELS.LIST_ID = ITEMS.MATTRESS_COMFORT_LEVELS_ID
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".PROMOTION_APPLIED_TO_VALUE ON PROMOTION_APPLIED_TO_VALUE.LIST_ID = ITEMS.PROMOTION_APPLIED_TO_ID
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".SEGMENT_LIST ON SEGMENT_LIST.LIST_ID = ITEMS.SEGMENT_ID
