SELECT
    TRANSACTIONS.TRANSACTION_ID,
    TRANSACTIONS.TRANDATE,
    TRANSACTIONS.TRANID,
    TRANSACTIONS.CUSTOMER_PHONE,
    TRANSACTION_LINES.LOCATION_ID,
    CLASSES.PRODUCT_GROUP_CODE,
    CLASSES.FULL_NAME,
    - SUM(TRANSACTION_LINES.ITEM_COUNT) AS 'ITEM_COUNT',
    - SUM(TRANSACTION_LINES.NET_AMOUNT) AS 'NET_AMOUNT'
FROM
    "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".TRANSACTION_LINES TRANSACTION_LINES
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".TRANSACTIONS TRANSACTIONS ON TRANSACTION_LINES.TRANSACTION_ID = TRANSACTIONS.TRANSACTION_ID
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".INVENTORY_ITEMS ON TRANSACTION_LINES.ITEM_ID = INVENTORY_ITEMS.ITEM_ID
    LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".CLASSES ON CLASSES.CLASS_ID = TRANSACTION_LINES.CLASS_ID
WHERE
    TRANSACTION_LINES.ACCOUNT_ID IN (
        480,
        482,
        487,
        498,
        505,
        508,
        509,
        510,
        511,
        54,
        1079,
        1170
    )
    AND TRANSACTIONS.TRANSACTION_TYPE IN ('Sales Order')
    AND TRANSACTIONS.STATUS <> 'Closed'
    AND (INVENTORY_ITEMS.DISPLAYNAME IS NOT NULL)
GROUP BY
    TRANSACTIONS.TRANDATE,
    TRANSACTIONS.TRANSACTION_ID,
    TRANSACTIONS.TRANID,
    TRANSACTIONS.CUSTOMER_PHONE,
    TRANSACTION_LINES.LOCATION_ID,
    TRANSACTION_LINES.ITEM_ID,
    CLASSES.PRODUCT_GROUP_CODE,
    CLASSES.FULL_NAME
