SELECT
	SYSTEM_NOTES.DATE_CREATED,
	SYSTEM_NOTES.ITEM_ID,
	SYSTEM_NOTES.VALUE_NEW,
	SYSTEM_NOTES.OPERATION
FROM
	"Vua Nem Joint Stock Company".Administrator.SYSTEM_NOTES
WHERE
	SYSTEM_NOTES.STANDARD_FIELD = 'RATE'
	AND SYSTEM_NOTES.ITEM_ID IS NOT NULL
