SELECT
	VENDORS.VENDOR_ID,
	VENDORS.NAME,
	VENDORS.FULL_NAME,
	VENDOR_TYPES.NAME AS 'VENDOR_TYPE'
FROM
	"Vua Nem Joint Stock Company".Administrator.VENDORS
	LEFT JOIN "Vua Nem Joint Stock Company".Administrator.VENDOR_TYPES ON VENDORS.VENDOR_TYPE_ID = VENDOR_TYPES.VENDOR_TYPE_ID
