from netsuite.pipeline.interface import Pipeline
from netsuite.repo import netsuite2_connection

pipeline = Pipeline(
    "ns2_promotionCode",
    [
        {"name": "enddate", "type": "TIMESTAMP"},
        {"name": "startdate", "type": "TIMESTAMP"},
        {"name": "discount", "type": "INTEGER"},
        {"name": "description", "type": "STRING"},
        {"name": "discounttype", "type": "STRING"},
        {"name": "discounteditemssavedsearch", "type": "INTEGER"},
        {"name": "displaylinediscounts", "type": "STRING"},
        {"name": "externalid", "type": "STRING"},
        {"name": "fixedprice", "type": "INTEGER"},
        {"name": "id", "type": "INTEGER"},
        {"name": "isinactive", "type": "STRING"},
        {"name": "itemquantifier", "type": "INTEGER"},
        {"name": "location", "type": "STRING"},
        {"name": "name", "type": "STRING"},
        {"name": "promotiontype", "type": "STRING"},
        {"name": "rate", "type": "FLOAT"},
        {"name": "repeatdiscount", "type": "STRING"},
        {"name": "lastmodifieddate", "type": "TIMESTAMP"},
        {"name": "custrecordissue_cho_bo_phan", "type": "STRING"},
        {"name": "custrecordmuc_dich_su_dung_voucher", "type": "STRING"},
        {"name": "custrecord_promotion_sm", "type": "STRING"},
        {"name": "custrecord_messenger_sms", "type": "STRING"},
        {"name": "custrecordpromotion_loai_vc2", "type": "STRING"},
        {"name": "custrecordpromo_doituong_ad", "type": "STRING"},
        {"name": "custrecordpromo_menhgia_vc", "type": "STRING"},
        {"name": "usetype", "type": "STRING"},
    ],
    netsuite2_connection,
    query_fn=lambda *args: """
        SELECT
            enddate,
            startdate,
            discount,
            description,
            discounttype,
            discounteditemssavedsearch,
            displaylinediscounts,
            externalid,
            fixedprice,
            id,
            isinactive,
            itemquantifier,
            location,
            name,
            promotiontype,
            rate,
            repeatdiscount,
            custrecordissue_cho_bo_phan,
            custrecordmuc_dich_su_dung_voucher,
            custrecord_promotion_sm,
            custrecord_messenger_sms,
            custrecordpromotion_loai_vc2,
            custrecordpromo_doituong_ad,
            custrecordpromo_menhgia_vc,
            usetype
        FROM
            promotionCode
    """,
)
