from netsuite.pipeline.interface import Pipeline, Key
from netsuite.repo import netsuite2_connection
from db.bigquery import timeframe_builder, update

pipeline = Pipeline(
    "ns2_transaction2",
    [
        {"name": "abbrevtype", "type": "STRING"},
        {"name": "accountbasednumber", "type": "STRING"},
        {"name": "actionitem", "type": "STRING"},
        {"name": "actualshipdate", "type": "TIMESTAMP"},
        {"name": "altsalestotal", "type": "NUMERIC"},
        {"name": "approvalstatus", "type": "NUMERIC"},
        {"name": "balsegstatus", "type": "NUMERIC"},
        {"name": "billingaddress", "type": "NUMERIC"},
        {"name": "billingstatus", "type": "STRING"},
        {"name": "bulkprocsubmission", "type": "NUMERIC"},
        {"name": "buyingreason", "type": "NUMERIC"},
        {"name": "buyingtimeframe", "type": "NUMERIC"},
        {"name": "closedate", "type": "TIMESTAMP"},
        {"name": "createdby", "type": "NUMERIC"},
        {"name": "createddate", "type": "TIMESTAMP"},
        {"name": "currency", "type": "NUMERIC"},
        {"name": "custbody1", "type": "STRING"},
        {"name": "custbody11", "type": "NUMERIC"},
        {"name": "custbody12", "type": "NUMERIC"},
        {"name": "custbody13", "type": "STRING"},
        {"name": "custbody14", "type": "STRING"},
        {"name": "custbody15", "type": "STRING"},
        {"name": "custbody16", "type": "STRING"},
        {"name": "custbody17", "type": "NUMERIC"},
        {"name": "custbody6", "type": "NUMERIC"},
        {"name": "custbody7", "type": "STRING"},
        {"name": "custbody_4110_customregnum", "type": "STRING"},
        {"name": "custbody_4599_mx_operation_type", "type": "NUMERIC"},
        {"name": "custbody_4599_sg_import_permit_num", "type": "STRING"},
        {"name": "custbody_actual_delivery_date", "type": "TIMESTAMP"},
        {"name": "custbody_actual_location", "type": "NUMERIC"},
        {"name": "custbody_adjustment_journal", "type": "STRING"},
        {"name": "custbody_approve_person", "type": "STRING"},
        {"name": "custbody_approved", "type": "STRING"},
        {"name": "custbody_approved_date", "type": "TIMESTAMP"},
        {"name": "custbody_cash_flow_code", "type": "STRING"},
        {"name": "custbody_cash_register", "type": "STRING"},
        {"name": "custbody_check_mass_update", "type": "STRING"},
        {"name": "custbody_chk_submit_customgl", "type": "STRING"},
        {"name": "custbody_citek_bien_ban_dchd", "type": "NUMERIC"},
        {"name": "custbody_citek_check_loyalty", "type": "STRING"},
        {"name": "custbody_closedreason", "type": "NUMERIC"},
        {"name": "custbody_counterparty_vat", "type": "STRING"},
        {"name": "custbody_country_of_origin", "type": "STRING"},
        {"name": "custbody_created_by", "type": "NUMERIC"},
        {"name": "custbody_cseg_new_segment", "type": "NUMERIC"},
        {"name": "custbody_current_partner", "type": "STRING"},
        {"name": "custbody_customer_phone", "type": "STRING"},
        {"name": "custbody_date_lsa", "type": "TIMESTAMP"},
        {"name": "custbody_date_of_taxable_supply", "type": "TIMESTAMP"},
        {"name": "custbody_delivery_instructions", "type": "STRING"},
        {"name": "custbody_delivery_person", "type": "NUMERIC"},
        {"name": "custbody_delivery_status", "type": "NUMERIC"},
        {"name": "custbody_delivery_terms", "type": "NUMERIC"},
        {"name": "custbody_delivery_vehicle", "type": "NUMERIC"},
        {"name": "custbody_deposit_payment_method", "type": "NUMERIC"},
        {"name": "custbody_distance", "type": "STRING"},
        {"name": "custbody_document_version", "type": "STRING"},
        {"name": "custbody_e_invoice_status", "type": "STRING"},
        {"name": "custbody_e_invoice_status_pxk", "type": "STRING"},
        {"name": "custbody_e_invoice_tbss_status", "type": "STRING"},
        {"name": "custbody_eddchanged", "type": "STRING"},
        {"name": "custbody_einvoice_no", "type": "STRING"},
        {"name": "custbody_einvoice_no_mau01", "type": "STRING"},
        {"name": "custbody_event", "type": "NUMERIC"},
        {"name": "custbody_expected_delivery_date_c", "type": "TIMESTAMP"},
        {"name": "custbody_expected_shipping_method", "type": "NUMERIC"},
        {"name": "custbody_expecteddeliverytime", "type": "NUMERIC"},
        {"name": "custbody_fam_jrn_is_reversal", "type": "STRING"},
        {"name": "custbody_fam_jrn_reversal_date", "type": "TIMESTAMP"},
        {"name": "custbody_fam_jrn_reversal_no", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_asset", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_assetdesc", "type": "STRING"},
        {"name": "custbody_fam_lp_assetprop", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_company", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_contract", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_contractnum", "type": "STRING"},
        {"name": "custbody_fam_lp_financelease", "type": "STRING"},
        {"name": "custbody_fam_lp_gainonmod", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_intexpense", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_leaseliability", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_rightofuse", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_startdate", "type": "TIMESTAMP"},
        {"name": "custbody_fam_lp_totalinterest", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_totalleaseliab", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_totalleasepayment", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_totalnpv", "type": "NUMERIC"},
        {"name": "custbody_fam_lp_totalprincipal", "type": "NUMERIC"},
        {"name": "custbody_fam_specdeprjrn_shortage", "type": "NUMERIC"},
        {"name": "custbody_fam_specdeprjrn_specialdepr", "type": "NUMERIC"},
        {"name": "custbody_gl_update_timestamp", "type": "TIMESTAMP"},
        {"name": "custbody_import_shipment_ref", "type": "NUMERIC"},
        {"name": "custbody_in_charge_location", "type": "NUMERIC"},
        {"name": "custbody_int_sync_to_vninvoice", "type": "STRING"},
        {"name": "custbody_int_sync_to_vninvoice03", "type": "STRING"},
        {"name": "custbody_invoice_date", "type": "TIMESTAMP"},
        {"name": "custbody_itr_doc_number", "type": "STRING"},
        {"name": "custbody_itr_nexus", "type": "STRING"},
        {"name": "custbody_journal_type", "type": "NUMERIC"},
        {"name": "custbody_journal_type2", "type": "NUMERIC"},
        {"name": "custbody_license_plate", "type": "STRING"},
        {"name": "custbody_license_plates", "type": "NUMERIC"},
        {"name": "custbody_link_lsa", "type": "STRING"},
        {"name": "custbody_link_name_lsa", "type": "STRING"},
        {"name": "custbody_mage_order_id", "type": "STRING"},
        {"name": "custbody_mage_order_number", "type": "STRING"},
        {"name": "custbody_mage_order_total", "type": "NUMERIC"},
        {"name": "custbody_mode_of_transport", "type": "NUMERIC"},
        {"name": "custbody_my_import_declaration_num", "type": "STRING"},
        {"name": "custbody_nexus_notc", "type": "NUMERIC"},
        {"name": "custbody_no_of_attempts", "type": "NUMERIC"},
        {"name": "custbody_nondeductible_processed", "type": "STRING"},
        {"name": "custbody_nondeductible_ref_genjrnl", "type": "NUMERIC"},
        {"name": "custbody_nondeductible_ref_tran", "type": "STRING"},
        {"name": "custbody_notc", "type": "NUMERIC"},
        {"name": "custbody_onl_rep", "type": "NUMERIC"},
        {"name": "custbody_order_payment_method", "type": "NUMERIC"},
        {"name": "custbody_payment_hold_reason", "type": "STRING"},
        {"name": "custbody_payment_trancode", "type": "STRING"},
        {"name": "custbody_pendingupdate", "type": "STRING"},
        {"name": "custbody_pendingupdate01", "type": "STRING"},
        {"name": "custbody_po_approval_status", "type": "NUMERIC"},
        {"name": "custbody_print_form", "type": "STRING"},
        {"name": "custbody_purchase_type", "type": "NUMERIC"},
        {"name": "custbody_recipient", "type": "STRING"},
        {"name": "custbody_recipient_phone", "type": "STRING"},
        {"name": "custbody_ref_doc_no", "type": "STRING"},
        {"name": "custbody_ref_invoice", "type": "NUMERIC"},
        {"name": "custbody_ref_multiple_transaction", "type": "STRING"},
        {"name": "custbody_ref_transaction", "type": "NUMERIC"},
        {"name": "custbody_reference_sales_order", "type": "NUMERIC"},
        {"name": "custbody_refno_originvoice", "type": "STRING"},
        {"name": "custbody_refund_payment_method", "type": "NUMERIC"},
        {"name": "custbody_regime_code", "type": "NUMERIC"},
        {"name": "custbody_regime_code_of_supply", "type": "NUMERIC"},
        {"name": "custbody_rejected", "type": "STRING"},
        {"name": "custbody_rejected_date", "type": "TIMESTAMP"},
        {"name": "custbody_report_timestamp", "type": "STRING"},
        {"name": "custbody_revision", "type": "NUMERIC"},
        {"name": "custbody_scv_external_transaction", "type": "STRING"},
        {"name": "custbody_sign_status", "type": "STRING"},
        {"name": "custbody_sign_status_03", "type": "STRING"},
        {"name": "custbody_so_billinginfor_address", "type": "STRING"},
        {"name": "custbody_so_billinginfor_name", "type": "STRING"},
        {"name": "custbody_so_billinginfor_taxno", "type": "STRING"},
        {"name": "custbody_submit_to_app", "type": "STRING"},
        {"name": "custbody_subsidiary_main", "type": "NUMERIC"},
        {"name": "custbody_supportperson", "type": "STRING"},
        {"name": "custbody_tbt_loyalty_sale_loy_cgrp_lvl", "type": "NUMERIC"},
        {"name": "custbody_tbt_loyalty_sale_loy_cust_grp", "type": "NUMERIC"},
        {"name": "custbody_tbt_loyalty_sale_loy_eli", "type": "STRING"},
        {"name": "custbody_tbt_loyalty_sale_loy_loc_grp", "type": "NUMERIC"},
        {"name": "custbody_tei_check_printed", "type": "STRING"},
        {"name": "custbody_tei_editing_counting", "type": "NUMERIC"},
        {"name": "custbody_tei_fam_vendor", "type": "STRING"},
        {"name": "custbody_tei_invoice_serial_no", "type": "STRING"},
        {"name": "custbody_tei_loyalty_expired_date", "type": "TIMESTAMP"},
        {"name": "custbody_tei_loyalty_remain_point", "type": "NUMERIC"},
        {"name": "custbody_tei_template_no", "type": "STRING"},
        {"name": "custbody_to_type", "type": "NUMERIC"},
        {"name": "custbody_transaction_code", "type": "STRING"},
        {"name": "custbody_transaction_region", "type": "NUMERIC"},
        {"name": "custbody_tvn_vnpay_message", "type": "STRING"},
        {"name": "custbody_tvn_vnpay_pos_id", "type": "NUMERIC"},
        {"name": "custbody_tvn_vnpay_status", "type": "NUMERIC"},
        {"name": "custbody_vendor_invoice_prefix", "type": "STRING"},
        {"name": "custbody_vnbi_voucher_adjustment", "type": "NUMERIC"},
        {"name": "custbody_vnpay_tran_code", "type": "STRING"},
        {"name": "custbody_vra_type", "type": "NUMERIC"},
        {"name": "custbody_wms_delivert_routing_status", "type": "NUMERIC"},
        {"name": "custbody_wms_delivery_rouitg_remarks", "type": "STRING"},
        {"name": "custbody_wms_delivery_routing_driver", "type": "NUMERIC"},
        {"name": "custbody_wms_delivery_shipping_person", "type": "NUMERIC"},
        {"name": "custbody_wms_delivery_time_stamp", "type": "STRING"},
        {"name": "custbody_wms_track_no", "type": "STRING"},
        {"name": "custbodycskh_da_goi_rating", "type": "NUMERIC"},
        {"name": "custbodycustbody_closedreason2", "type": "NUMERIC"},
        {"name": "custbodycustbodycskh_da_goi_vesinhdem", "type": "NUMERIC"},
        {"name": "custbodycustome_return_reason2", "type": "NUMERIC"},
        {"name": "custbodyexpected_shipdate_to", "type": "TIMESTAMP"},
        {"name": "custbodykho_da_goi", "type": "STRING"},
        {"name": "custbodypo_delivery_status", "type": "NUMERIC"},
        {"name": "custbodyservice_add_on", "type": "STRING"},
        {"name": "custbodyservice_add_on_to", "type": "STRING"},
        {"name": "custbodysotienthuengoai", "type": "NUMERIC"},
        {"name": "custbodythoi_gian_xuat_kho_gio", "type": "NUMERIC"},
        {"name": "custbodythoi_gian_xuat_kho_phut", "type": "NUMERIC"},
        {"name": "custbodyvanchuyen_note", "type": "STRING"},
        {"name": "custbodywarehouse_person", "type": "STRING"},
        {"name": "daysopen", "type": "NUMERIC"},
        {"name": "daysoverduesearch", "type": "NUMERIC"},
        {"name": "duedate", "type": "TIMESTAMP"},
        {"name": "email", "type": "STRING"},
        {"name": "employee", "type": "NUMERIC"},
        {"name": "enddate", "type": "TIMESTAMP"},
        {"name": "entity", "type": "NUMERIC"},
        {"name": "entitystatus", "type": "NUMERIC"},
        {"name": "estgrossprofit", "type": "NUMERIC"},
        {"name": "estgrossprofitpercent", "type": "NUMERIC"},
        {"name": "estimatedbudget", "type": "NUMERIC"},
        {"name": "exchangerate", "type": "NUMERIC"},
        {"name": "expectedclosedate", "type": "TIMESTAMP"},
        {"name": "externalid", "type": "STRING"},
        {"name": "fax", "type": "STRING"},
        {"name": "firmed", "type": "STRING"},
        {"name": "forecasttype", "type": "NUMERIC"},
        {"name": "foreignamountpaid", "type": "NUMERIC"},
        {"name": "foreignamountunpaid", "type": "NUMERIC"},
        {"name": "foreignpaymentamountunused", "type": "NUMERIC"},
        {"name": "foreignpaymentamountused", "type": "NUMERIC"},
        {"name": "foreigntotal", "type": "NUMERIC"},
        {"name": "fulfillmenttype", "type": "NUMERIC"},
        {"name": "id", "type": "NUMERIC"},
        {"name": "incoterm", "type": "NUMERIC"},
        {"name": "intercostatus", "type": "NUMERIC"},
        {"name": "intercotransaction", "type": "NUMERIC"},
        {"name": "isbudgetapproved", "type": "STRING"},
        {"name": "isfinchrg", "type": "STRING"},
        {"name": "isreversal", "type": "STRING"},
        {"name": "journaltype", "type": "STRING"},
        {"name": "lastmodifiedby", "type": "NUMERIC"},
        {"name": "lastmodifieddate", "type": "TIMESTAMP"},
        {"name": "leadsource", "type": "NUMERIC"},
        {"name": "linkedtrackingnumberlist", "type": "STRING"},
        {"name": "memdoc", "type": "NUMERIC"},
        {"name": "memo", "type": "STRING"},
        {"name": "message", "type": "STRING"},
        {"name": "netaltsalestotal", "type": "NUMERIC"},
        {"name": "nextapprover", "type": "NUMERIC"},
        {"name": "nextbilldate", "type": "TIMESTAMP"},
        {"name": "nexus", "type": "NUMERIC"},
        {"name": "number", "type": "NUMERIC"},
        {"name": "opportunity", "type": "NUMERIC"},
        {"name": "ordpicked", "type": "STRING"},
        {"name": "ordreceived", "type": "STRING"},
        {"name": "otherrefnum", "type": "STRING"},
        {"name": "partner", "type": "NUMERIC"},
        {"name": "paymenthold", "type": "STRING"},
        {"name": "paymentmethod", "type": "NUMERIC"},
        {"name": "paymentoption", "type": "NUMERIC"},
        {"name": "posting", "type": "STRING"},
        {"name": "postingperiod", "type": "NUMERIC"},
        {"name": "printedpickingticket", "type": "STRING"},
        {"name": "probability", "type": "NUMERIC"},
        {"name": "projectedtotal", "type": "NUMERIC"},
        {"name": "promotioncombinations", "type": "STRING"},
        {"name": "rangehigh", "type": "NUMERIC"},
        {"name": "rangelow", "type": "NUMERIC"},
        {"name": "recordtype", "type": "STRING"},
        {"name": "reversal", "type": "NUMERIC"},
        {"name": "reversaldate", "type": "TIMESTAMP"},
        {"name": "revision", "type": "NUMERIC"},
        {"name": "salesreadiness", "type": "NUMERIC"},
        {"name": "shipcarrier", "type": "STRING"},
        {"name": "shipcomplete", "type": "STRING"},
        {"name": "shipdate", "type": "TIMESTAMP"},
        {"name": "shippingaddress", "type": "NUMERIC"},
        {"name": "source", "type": "STRING"},
        {"name": "sourcetransaction", "type": "NUMERIC"},
        {"name": "startdate", "type": "TIMESTAMP"},
        {"name": "status", "type": "STRING"},
        {"name": "terms", "type": "NUMERIC"},
        {"name": "title", "type": "STRING"},
        {"name": "tosubsidiary", "type": "NUMERIC"},
        {"name": "totalcostestimate", "type": "NUMERIC"},
        {"name": "trackingnumberlist", "type": "STRING"},
        {"name": "trandate", "type": "TIMESTAMP"},
        {"name": "trandisplayname", "type": "STRING"},
        {"name": "tranid", "type": "STRING"},
        {"name": "transactionnumber", "type": "STRING"},
        {"name": "transferlocation", "type": "NUMERIC"},
        {"name": "type", "type": "STRING"},
        {"name": "typebaseddocumentnumber", "type": "STRING"},
        {"name": "useitemcostastransfercost", "type": "STRING"},
        {"name": "userevenuearrangement", "type": "STRING"},
        {"name": "visibletocustomer", "type": "STRING"},
        {"name": "void", "type": "STRING"},
        {"name": "voided", "type": "STRING"},
        {"name": "website", "type": "NUMERIC"},
        {"name": "weightedtotal", "type": "NUMERIC"},
        {"name": "winlossreason", "type": "NUMERIC"},
    ],
    conn_fn=netsuite2_connection,
    query_fn=lambda tr: f"""
        SELECT
            abbrevtype,
            accountbasednumber,
            actionitem,
            actualshipdate,
            altsalestotal,
            approvalstatus,
            balsegstatus,
            billingaddress,
            billingstatus,
            bulkprocsubmission,
            buyingreason,
            buyingtimeframe,
            closedate,
            createdby,
            createddate,
            currency,
            custbody1,
            custbody11,
            custbody12,
            custbody13,
            custbody14,
            custbody15,
            custbody16,
            custbody17,
            custbody6,
            custbody7,
            custbody_4110_customregnum,
            custbody_4599_mx_operation_type,
            custbody_4599_sg_import_permit_num,
            custbody_actual_delivery_date,
            custbody_actual_location,
            custbody_adjustment_journal,
            custbody_approve_person,
            custbody_approved,
            custbody_approved_date,
            custbody_cash_flow_code,
            custbody_cash_register,
            custbody_check_mass_update,
            custbody_chk_submit_customgl,
            custbody_citek_bien_ban_dchd,
            custbody_citek_check_loyalty,
            custbody_closedreason,
            custbody_counterparty_vat,
            custbody_country_of_origin,
            custbody_created_by,
            custbody_cseg_new_segment,
            custbody_current_partner,
            custbody_customer_phone,
            custbody_date_lsa,
            custbody_date_of_taxable_supply,
            custbody_delivery_instructions,
            custbody_delivery_person,
            custbody_delivery_status,
            custbody_delivery_terms,
            custbody_delivery_vehicle,
            custbody_deposit_payment_method,
            custbody_distance,
            custbody_document_version,
            custbody_e_invoice_status,
            custbody_e_invoice_status_pxk,
            custbody_e_invoice_tbss_status,
            custbody_eddchanged,
            custbody_einvoice_no,
            custbody_einvoice_no_mau01,
            custbody_event,
            custbody_expected_delivery_date_c,
            custbody_expected_shipping_method,
            custbody_expecteddeliverytime,
            custbody_fam_jrn_is_reversal,
            custbody_fam_jrn_reversal_date,
            custbody_fam_jrn_reversal_no,
            custbody_fam_lp_asset,
            custbody_fam_lp_assetdesc,
            custbody_fam_lp_assetprop,
            custbody_fam_lp_company,
            custbody_fam_lp_contract,
            custbody_fam_lp_contractnum,
            custbody_fam_lp_financelease,
            custbody_fam_lp_gainonmod,
            custbody_fam_lp_intexpense,
            custbody_fam_lp_leaseliability,
            custbody_fam_lp_rightofuse,
            custbody_fam_lp_startdate,
            custbody_fam_lp_totalinterest,
            custbody_fam_lp_totalleaseliab,
            custbody_fam_lp_totalleasepayment,
            custbody_fam_lp_totalnpv,
            custbody_fam_lp_totalprincipal,
            custbody_fam_specdeprjrn_shortage,
            custbody_fam_specdeprjrn_specialdepr,
            custbody_gl_update_timestamp,
            custbody_import_shipment_ref,
            custbody_in_charge_location,
            custbody_int_sync_to_vninvoice,
            custbody_int_sync_to_vninvoice03,
            custbody_invoice_date,
            custbody_itr_doc_number,
            custbody_itr_nexus,
            custbody_journal_type,
            custbody_journal_type2,
            custbody_license_plate,
            custbody_license_plates,
            custbody_link_lsa,
            custbody_link_name_lsa,
            custbody_mage_order_id,
            custbody_mage_order_number,
            custbody_mage_order_total,
            custbody_mode_of_transport,
            custbody_my_import_declaration_num,
            custbody_nexus_notc,
            custbody_no_of_attempts,
            custbody_nondeductible_processed,
            custbody_nondeductible_ref_genjrnl,
            custbody_nondeductible_ref_tran,
            custbody_notc,
            custbody_onl_rep,
            custbody_order_payment_method,
            custbody_payment_hold_reason,
            custbody_payment_trancode,
            custbody_pendingupdate,
            custbody_pendingupdate01,
            custbody_po_approval_status,
            custbody_print_form,
            custbody_purchase_type,
            custbody_recipient,
            custbody_recipient_phone,
            custbody_ref_doc_no,
            custbody_ref_invoice,
            custbody_ref_multiple_transaction,
            custbody_ref_transaction,
            custbody_reference_sales_order,
            custbody_refno_originvoice,
            custbody_refund_payment_method,
            custbody_regime_code,
            custbody_regime_code_of_supply,
            custbody_rejected,
            custbody_rejected_date,
            custbody_report_timestamp,
            custbody_revision,
            custbody_scv_external_transaction,
            custbody_sign_status,
            custbody_sign_status_03,
            custbody_so_billinginfor_address,
            custbody_so_billinginfor_name,
            custbody_so_billinginfor_taxno,
            custbody_submit_to_app,
            custbody_subsidiary_main,
            custbody_supportperson,
            custbody_tbt_loyalty_sale_loy_cgrp_lvl,
            custbody_tbt_loyalty_sale_loy_cust_grp,
            custbody_tbt_loyalty_sale_loy_eli,
            custbody_tbt_loyalty_sale_loy_loc_grp,
            custbody_tei_check_printed,
            custbody_tei_editing_counting,
            custbody_tei_fam_vendor,
            custbody_tei_invoice_serial_no,
            custbody_tei_loyalty_expired_date,
            custbody_tei_loyalty_remain_point,
            custbody_tei_template_no,
            custbody_to_type,
            custbody_transaction_code,
            custbody_transaction_region,
            custbody_tvn_vnpay_message,
            custbody_tvn_vnpay_pos_id,
            custbody_tvn_vnpay_status,
            custbody_vendor_invoice_prefix,
            custbody_vnbi_voucher_adjustment,
            custbody_vnpay_tran_code,
            custbody_vra_type,
            custbody_wms_delivert_routing_status,
            custbody_wms_delivery_rouitg_remarks,
            custbody_wms_delivery_routing_driver,
            custbody_wms_delivery_shipping_person,
            custbody_wms_delivery_time_stamp,
            custbody_wms_track_no,
            custbodycskh_da_goi_rating,
            custbodycustbody_closedreason2,
            custbodycustbodycskh_da_goi_vesinhdem,
            custbodycustome_return_reason2,
            custbodyexpected_shipdate_to,
            custbodykho_da_goi,
            custbodypo_delivery_status,
            custbodyservice_add_on,
            custbodyservice_add_on_to,
            custbodysotienthuengoai,
            custbodythoi_gian_xuat_kho_gio,
            custbodythoi_gian_xuat_kho_phut,
            custbodyvanchuyen_note,
            custbodywarehouse_person,
            daysopen,
            daysoverduesearch,
            duedate,
            email,
            employee,
            enddate,
            entity,
            entitystatus,
            estgrossprofit,
            estgrossprofitpercent,
            estimatedbudget,
            exchangerate,
            expectedclosedate,
            externalid,
            fax,
            firmed,
            forecasttype,
            foreignamountpaid,
            foreignamountunpaid,
            foreignpaymentamountunused,
            foreignpaymentamountused,
            foreigntotal,
            fulfillmenttype,
            id,
            incoterm,
            intercostatus,
            intercotransaction,
            isbudgetapproved,
            isfinchrg,
            isreversal,
            journaltype,
            lastmodifiedby,
            lastmodifieddate,
            leadsource,
            linkedtrackingnumberlist,
            memdoc,
            memo,
            message,
            netaltsalestotal,
            nextapprover,
            nextbilldate,
            nexus,
            number,
            opportunity,
            ordpicked,
            ordreceived,
            otherrefnum,
            partner,
            paymenthold,
            paymentmethod,
            paymentoption,
            posting,
            postingperiod,
            printedpickingticket,
            probability,
            projectedtotal,
            promotioncombinations,
            rangehigh,
            rangelow,
            recordtype,
            reversal,
            reversaldate,
            revision,
            salesreadiness,
            shipcarrier,
            shipcomplete,
            shipdate,
            shippingaddress,
            source,
            sourcetransaction,
            startdate,
            status,
            terms,
            title,
            tosubsidiary,
            totalcostestimate,
            trackingnumberlist,
            trandate,
            trandisplayname,
            tranid,
            transactionnumber,
            transferlocation,
            type,
            typebaseddocumentnumber,
            useitemcostastransfercost,
            userevenuearrangement,
            visibletocustomer,
            void,
            voided,
            website,
            weightedtotal,
            winlossreason
        FROM
            transaction
        WHERE
            lastmodifieddate >= TO_DATE('{tr[0]}', 'YYYY-MM-DD HH24:MI:SS')
            AND lastmodifieddate <= TO_DATE('{tr[1]}', 'YYYY-MM-DD HH24:MI:SS')
    """,
    param_fn=timeframe_builder,
    key=Key(
        id_key=["id"],
        cursor_key=["lastmodifieddate"],
    ),
    load_callback_fn=update,
)
