from pipelines import NetSuiteJob


class CUSTOMERS(NetSuiteJob):
    query = """
    SELECT
        CUSTOMERS.CUSTOMER_ID,
        CUSTOMERS.PHONE,
        CUSTOMERS.EMAIL,
        CUSTOMERS.CATEGORY_0,
        CUSTOMERS.FULL_NAME,
        CUSTOMERS.FIRSTNAME,
        CUSTOMERS.MIDDLENAME,
        CUSTOMERS.LASTNAME,
        CUSTOMERS.NAME,
        CUSTOMERS.BILLADDRESS,
        CUSTOMERS.SHIPADDRESS,
        CUSTOMERS.CITY,
        CUSTOMERS.COMPANYNAME,
        CUSTOMERS.CONVERTED_TO_ID,
        CUSTOMERS.COUNTRY,
        CUSTOMERS.CREATE_DATE,
        CUSTOMERS.DATE_CLOSED,
        CUSTOMERS.DATE_CONVSERSION,
        CUSTOMERS.DATE_FIRST_ORDER,
        CUSTOMERS.DATE_FIRST_SALE,
        CUSTOMERS.DATE_LAST_MODIFIED,
        CUSTOMERS.DATE_LAST_ORDER,
        CUSTOMERS.DATE_LAST_SALE,
        CUSTOMERS.DATE_LEAD,
        CUSTOMERS.DATE_PROSPECT,
        CUSTOMERS.FROM_CAMPAIGN,
        CUSTOMERS.FROM_LANDING,
        CUSTOMERS.HOME_PHONE,
        CUSTOMERS.ISINACTIVE,
        CUSTOMERS.LAST_MODIFIED_DATE,
        CUSTOMERS.LEAD_SOURCE_ID,
        CUSTOMERS.SMS_PROMO_ID,
        CUSTOMERS.SOURCES_ID,
        CUSTOMERS.STATUS,
        CUSTOMERS.SUBSIDIARY_ID
    FROM
        "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".CUSTOMERS
    """

    schema = [
        {"name": "CUSTOMER_ID", "type": "INTEGER"},
        {"name": "PHONE", "type": "STRING"},
        {"name": "EMAIL", "type": "STRING"},
        {"name": "CATEGORY_0", "type": "STRING"},
        {"name": "FULL_NAME", "type": "STRING"},
        {"name": "FIRSTNAME", "type": "STRING"},
        {"name": "MIDDLENAME", "type": "STRING"},
        {"name": "LASTNAME", "type": "INTEGER"},
        {"name": "NAME", "type": "TIMESTAMP"},
        {"name": "BILLADDRESS", "type": "STRING"},
        {"name": "SHIPADDRESS", "type": "STRING"},
        {"name": "CITY", "type": "STRING"},
        {"name": "COMPANYNAME", "type": "STRING"},
        {"name": "CONVERTED_TO_ID", "type": "INTEGER"},
        {"name": "COUNTRY", "type": "STRING"},
        {"name": "CREATE_DATE", "type": "TIMESTAMP"},
        {"name": "DATE_CLOSED", "type": "TIMESTAMP"},
        {"name": "DATE_CONVERSION", "type": "TIMESTAMP"},
        {"name": "DATE_FIRST_ORDER", "type": "TIMESTAMP"},
        {"name": "DATE_FIRST_SALE", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_MODIFIED", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_ORDER", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_SALE", "type": "TIMESTAMP"},
        {"name": "DATE_LEAD", "type": "TIMESTAMP"},
        {"name": "DATE_PROSPECT", "type": "TIMESTAMP"},
        {"name": "FROM_CAMPAIGN", "type": "STRING"},
        {"name": "FROM_LANDING", "type": "STRING"},
        {"name": "HOME_PHONE", "type": "STRING"},
        {"name": "ISINACTIVE", "type": "STRING"},
        {"name": "LAST_MODIFIED_DATE", "type": "TIMESTAMP"},
        {"name": "LEAD_SOURCE_ID", "type": "INTEGER"},
        {"name": "SMS_PROMO_ID", "type": "STRING"},
        {"name": "SOURCES_ID", "type": "INTEGER"},
        {"name": "STATUS", "type": "STRING"},
        {"name": "SUBSIDIARY_ID", "type": "INTEGER"},
    ]
