from pipelines import NetSuiteJob


class EMPLOYEES(NetSuiteJob):
    query = """
    SELECT
        EMPLOYEES.EMPLOYEE_ID,
        EMPLOYEES.VN_CODE,
        EMPLOYEES.FULL_NAME,
        EMPLOYEES.FIRSTNAME,
        EMPLOYEES.MIDDLENAME,
        EMPLOYEES.LASTNAME,
        EMPLOYEES.NAME,
        EMPLOYEES.JOBTITLE,
        EMPLOYEES.PHONE,
        EMPLOYEES.MOBILE_PHONE,
        EMPLOYEES.EMAIL,
        EMPLOYEES.GENDER,
        EMPLOYEES.BIRTHDATE,
        EMPLOYEES.COMMENTS,
        EMPLOYEES.CREATE_DATE,
        EMPLOYEES.DATE_LAST_MODIFIED,
        EMPLOYEES.LAST_MODIFIED_DATE,
        EMPLOYEES.HIREDDATE,
        EMPLOYEES.ONBOARDING_DATE,
        EMPLOYEES.RELEASEDATE,
        EMPLOYEES.RELEASE_REASON_ID,
        EMPLOYEES.DELIVERY_PERSON,
        EMPLOYEES.DEPARTMENT_ID,
        EMPLOYEES.LOCATION_ID,
        EMPLOYEES.EMPLOYEE_TYPE_ID,
        EMPLOYEES.IDENTITY_NO_,
        EMPLOYEES.IDENTITY_PROVIDED_AGENCY,
        EMPLOYEES.IDENTITY_PROVIDED_DATE,
        EMPLOYEES.ISINACTIVE,
        EMPLOYEES.ISSALESREP,
        EMPLOYEES.JOB_DESCRIPTION,
        EMPLOYEES.STATUS,
        EMPLOYEES.SUBSIDIARY_ID,
        EMPLOYEES.SUPERVISOR_ID
    FROM
        "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".EMPLOYEES
    """

    schema = [
        {"name": "EMPLOYEE_ID", "type": "INTEGER"},
        {"name": "VN_CODE", "type": "STRING"},
        {"name": "FULL_NAME", "type": "STRING"},
        {"name": "FIRSTNAME", "type": "STRING"},
        {"name": "MIDDLENAME", "type": "STRING"},
        {"name": "LASTNAME", "type": "STRING"},
        {"name": "NAME", "type": "STRING"},
        {"name": "JOBTITLE", "type": "STRING"},
        {"name": "PHONE", "type": "STRING"},
        {"name": "MOBILE_PHONE", "type": "STRING"},
        {"name": "EMAIL", "type": "STRING"},
        {"name": "GENDER", "type": "STRING"},
        {"name": "BIRTHDATE", "type": "TIMESTAMP"},
        {"name": "COMMENTS", "type": "STRING"},
        {"name": "CREATE_DATE", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_MODIFIED", "type": "TIMESTAMP"},
        {"name": "LAST_MODIFIED_DATE", "type": "TIMESTAMP"},
        {"name": "HIREDDATE", "type": "TIMESTAMP"},
        {"name": "ONBOARDING_DATE", "type": "TIMESTAMP"},
        {"name": "RELEASEDATE", "type": "TIMESTAMP"},
        {"name": "RELEASE_REASON_ID", "type": "INTEGER"},
        {"name": "DELIVERY_PERSON", "type": "STRING"},
        {"name": "DEPARTMENT_ID", "type": "INTEGER"},
        {"name": "LOCATION_ID", "type": "INTEGER"},
        {"name": "EMPLOYEE_TYPE_ID", "type": "STRING"},
        {"name": "IDENTITY_NO_", "type": "STRING"},
        {"name": "IDENTITY_PROVIDED_AGENCY", "type": "STRING"},
        {"name": "IDENTITY_PROVIDED_DATE", "type": "TIMESTAMP"},
        {"name": "ISINACTIVE", "type": "STRING"},
        {"name": "ISSALESREP", "type": "STRING"},
        {"name": "JOB_DESCRIPTION", "type": "STRING"},
        {"name": "STATUS", "type": "STRING"},
        {"name": "SUBSIDIARY_ID", "type": "INTEGER"},
        {"name": "SUPERVISOR_ID", "type": "INTEGER"},
    ]
