name: Build & Deploy
on:
  push:
    branches:
      - incremental
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  TOPIC: vuanem_ns
  SERVICE: vuanem-ns
  DISPATCHER_NAME: vuanem_ns_dispatcher
  REGION: us-central1

jobs:
  vuanem-ns:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}

    - name: Deploy to Main module to Cloud Run
      run: >-
        gcloud run deploy ${{ env.SERVICE }}
        --image=gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        --concurrency=1
        --memory=1Gi
        --cpu=2
        --platform=managed
        --service-account=${{ secrets.GCP_SA }}
        --region=${{ env.REGION }}
        --timeout=900
        --set-env-vars=ACCOUNT_ID=${{ secrets.ACCOUNT_ID }},ROLE_ID=${{ secrets.ROLE_ID }},NS_DSN=${{ secrets.NS_DSN }},NS_UID=${{ secrets.NS_UID }},NS_PWD=${{ secrets.NS_PWD }},TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}

  dispatcher:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Deploy Invoker to Cloud Function
      run: >-
        python invoker/build.py
        &&
        gcloud functions deploy ${{ env.DISPATCHER_NAME }}
        --source=invoker
        --entry-point=main
        --runtime=python38
        --trigger-http
        --project=${{ secrets.PROJECT_ID }}
        --service-account=${{ secrets.GCP_SA }}
