from sqlalchemy import Column, Integer, String, DateTime

from models.models import NetSuite
from components import connector
from components import getter
from components import loader


class CUSTOMERS(NetSuite):
    keys = {
        "p_key": ["CUSTOMER_ID"],
        "rank_key": ["CUSTOMER_ID"],
        "incre_key": ["DATE_LAST_MODIFIED"],
        "rank_incre_key": ["DATE_LAST_MODIFIED"],
        "row_num_incre_key": ["DATE_LAST_MODIFIED"],
    }
    query = """
        SELECT
            CUSTOMER_ID,
            PHONE,
            EMAIL,
            CATEGORY_0,
            FULL_NAME,
            FIRSTNAME,
            MIDDLENAME,
            LASTNAME,
            NAME,
            BILLADDRESS,
            SHIPADDRESS,
            CITY,
            COMPANYNAME,
            CONVERTED_TO_ID,
            COUNTRY,
            CREATE_DATE,
            DATE_CLOSED,
            DATE_CONVSERSION,
            DATE_FIRST_ORDER,
            DATE_FIRST_SALE,
            DATE_LAST_MODIFIED,
            DATE_LAST_ORDER,
            DATE_LAST_SALE,
            DATE_LEAD,
            DATE_PROSPECT,
            FROM_CAMPAIGN,
            FROM_LANDING,
            HOME_PHONE,
            ISINACTIVE,
            LAST_MODIFIED_DATE,
            LEAD_SOURCE_ID,
            SMS_PROMO_ID,
            SOURCES_ID,
            STATUS,
            SUBSIDIARY_ID,
            DATE_OF_BIRTH,
            LOYALTY_GROUP_ID
        FROM
            "Vua Nem Joint Stock Company".Administrator.CUSTOMERS
        WHERE
            DATE_LAST_MODIFIED >= '{{ start }}'
            AND DATE_LAST_MODIFIED <= '{{ end }}'
    """
    schema = [
        {"name": "CUSTOMER_ID", "type": "INTEGER"},
        {"name": "PHONE", "type": "STRING"},
        {"name": "EMAIL", "type": "STRING"},
        {"name": "CATEGORY_0", "type": "STRING"},
        {"name": "FULL_NAME", "type": "STRING"},
        {"name": "FIRSTNAME", "type": "STRING"},
        {"name": "MIDDLENAME", "type": "STRING"},
        {"name": "LASTNAME", "type": "STRING"},
        {"name": "NAME", "type": "STRING"},
        {"name": "BILLADDRESS", "type": "STRING"},
        {"name": "SHIPADDRESS", "type": "STRING"},
        {"name": "CITY", "type": "STRING"},
        {"name": "COMPANYNAME", "type": "STRING"},
        {"name": "CONVERTED_TO_ID", "type": "INTEGER"},
        {"name": "COUNTRY", "type": "STRING"},
        {"name": "CREATE_DATE", "type": "TIMESTAMP"},
        {"name": "DATE_CLOSED", "type": "TIMESTAMP"},
        {"name": "DATE_CONVSERSION", "type": "TIMESTAMP"},
        {"name": "DATE_FIRST_ORDER", "type": "TIMESTAMP"},
        {"name": "DATE_FIRST_SALE", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_MODIFIED", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_ORDER", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_SALE", "type": "TIMESTAMP"},
        {"name": "DATE_LEAD", "type": "TIMESTAMP"},
        {"name": "DATE_PROSPECT", "type": "TIMESTAMP"},
        {"name": "FROM_CAMPAIGN", "type": "STRING"},
        {"name": "FROM_LANDING", "type": "STRING"},
        {"name": "HOME_PHONE", "type": "STRING"},
        {"name": "ISINACTIVE", "type": "STRING"},
        {"name": "LAST_MODIFIED_DATE", "type": "TIMESTAMP"},
        {"name": "LEAD_SOURCE_ID", "type": "INTEGER"},
        {"name": "SMS_PROMO_ID", "type": "STRING"},
        {"name": "SOURCES_ID", "type": "INTEGER"},
        {"name": "STATUS", "type": "STRING"},
        {"name": "SUBSIDIARY_ID", "type": "INTEGER"},
        {"name": "DATE_OF_BIRTH", "type": "TIMESTAMP"},
        {"name": "LOYALTY_GROUP_ID", "type": "INTEGER"},
    ]
    columns = [
        Column("CUSTOMER_ID", Integer, primary_key=True),
        Column("PHONE", String),
        Column("EMAIL", String),
        Column("CATEGORY_0", String),
        Column("FULL_NAME", String),
        Column("FIRSTNAME", String),
        Column("MIDDLENAME", String),
        Column("LASTNAME", String),
        Column("NAME", String),
        Column("BILLADDRESS", String),
        Column("SHIPADDRESS", String),
        Column("CITY", String),
        Column("COMPANYNAME", String),
        Column("CONVERTED_TO_ID", Integer),
        Column("COUNTRY", String),
        Column("CREATE_DATE", DateTime(timezone=True)),
        Column("DATE_CLOSED", DateTime(timezone=True)),
        Column("DATE_CONVSERSION", DateTime(timezone=True)),
        Column("DATE_FIRST_ORDER", DateTime(timezone=True)),
        Column("DATE_FIRST_SALE", DateTime(timezone=True)),
        Column("DATE_LAST_MODIFIED", DateTime(timezone=True)),
        Column("DATE_LAST_ORDER", DateTime(timezone=True)),
        Column("DATE_LAST_SALE", DateTime(timezone=True)),
        Column("DATE_LEAD", DateTime(timezone=True)),
        Column("DATE_PROSPECT", DateTime(timezone=True)),
        Column("FROM_CAMPAIGN", String),
        Column("FROM_LANDING", String),
        Column("HOME_PHONE", String),
        Column("ISINACTIVE", String),
        Column("LAST_MODIFIED_DATE", DateTime(timezone=True)),
        Column("LEAD_SOURCE_ID", Integer),
        Column("SMS_PROMO_ID", String),
        Column("SOURCES_ID", Integer),
        Column("STATUS", String),
        Column("SUBSIDIARY_ID", Integer),
        Column("DATE_OF_BIRTH", DateTime(timezone=True)),
        Column("LOYALTY_GROUP_ID", DateTime(timezone=True)),
    ]
    connector = connector.NetSuiteConnector
    getter = getter.TimeIncrementalGetter
    loader = [
        loader.PostgresIncrementalLoader,
        loader.BigQueryIncrementalLoader,
    ]
