from sqlalchemy import Column, Integer, String, DateTime

from models.models import NetSuite
from components import connector
from components import getter
from components import loader


class ENTITY(NetSuite):
    keys = {
        "p_key": ["ENTITY_ID"],
        "rank_key": ["ENTITY_ID"],
        "incre_key": ["DATE_LAST_MODIFIED"],
        "rank_incre_key": ["DATE_LAST_MODIFIED"],
        "row_num_incre_key": ["DATE_LAST_MODIFIED"],
    }
    query = """
        SELECT
            ACCOUNT_OWNER_NAME,
            ADDRESS_ONE,
            ADDRESS_THREE,
            ADDRESS_TWO,
            APPROVE_PERSON,
            BANKS_BRANCH,
            BANK_ACCOUNT,
            BANK_NAME,
            BLOCK_SMS,
            BRANCH,
            CITY,
            COUNTRY,
            CREATE_DATE,
            DATE_LAST_MODIFIED,
            DATE_OF_BIRTH,
            DATE_UPDATED,
            DEFAULT_AP_ACCOUNT_ID,
            DELIVERY_PERSON,
            DIC,
            EMAIL,
            EMPLOYEE_RECORD_REFERENCE_ID,
            ENTITY_CODE,
            ENTITY_EXTID,
            ENTITY_ID,
            ENTITY_TYPE,
            EXPIRATION_DATE_FOR_LOYALTY_S,
            FIRST_NAME,
            FROM_CAMPAIGN,
            FROM_LANDING,
            FULL_NAME,
            GLOBAL_SUBSCRIPTION_STATUS,
            ICO,
            IDENTITY_NO_,
            IDENTITY_PROVIDED_AGENCY,
            IDENTITY_PROVIDED_DATE,
            ISRELEASEDCOACHING,
            IS_INACTIVE,
            IS_LEAD__BN_BUN,
            IS_ONLINE_BILL_PAY,
            IS_UNAVAILABLE,
            LAST_MODIFIED_DATE,
            LAST_NAME,
            LAST_SALES_ACTIVITY,
            LOGIN_ACCESS,
            LOYALTY_ELIGIBILITY,
            LOYALTY_GROUP_ID,
            LOYALTY_GROUP_LEVEL,
            LOYALTY_REMAINING_POINT_VALUE,
            LOYALTY_SMS_VALUE_PENDING_UPD,
            LSA_LINK,
            LSA_LINK_NAME,
            MIDDLE_NAME,
            NAME,
            NEW_SEGMENT_ID,
            NGY_TO_LEAD,
            NOTES,
            N__GI_RATING_ID,
            ONBOARDING_DATE,
            ORIGINATOR_ID,
            PARENT_ID,
            PARTNER_RECORD_REFERENCE_ID,
            PERMISSION_CHECK_PRINT,
            PHONE,
            RELEASE_REASON_ID,
            SALES_REP_JOB_TITLE_ID,
            SALUTATION,
            SMS_FOR_EXP_DATE,
            SMS_PROMO_ID,
            SMS_SENT_DATE,
            SOURCES_ID,
            SPECIAL_DISCOUNT,
            STATE,
            SUBSIDIARY,
            TAX_CONTACT_FIRST_NAME,
            TAX_CONTACT_ID,
            TAX_CONTACT_LAST_NAME,
            TAX_CONTACT_MIDDLE_NAME,
            UNSUBSCRIBED,
            UPDATE_TIMESTAMP,
            VAT_REGISTRATION_NO,
            VN_CODE,
            ZIPCODE
        FROM
            "Vua Nem Joint Stock Company".Administrator.ENTITY
        WHERE
            DATE_LAST_MODIFIED >= '{{ start }}'
            AND DATE_LAST_MODIFIED <= '{{ end }}'

    """
    schema = [
        {"name": "ACCOUNT_OWNER_NAME", "type": "STRING"},
        {"name": "ADDRESS_ONE", "type": "STRING"},
        {"name": "ADDRESS_THREE", "type": "STRING"},
        {"name": "ADDRESS_TWO", "type": "STRING"},
        {"name": "APPROVE_PERSON", "type": "STRING"},
        {"name": "BANKS_BRANCH", "type": "STRING"},
        {"name": "BANK_ACCOUNT", "type": "STRING"},
        {"name": "BANK_NAME", "type": "STRING"},
        {"name": "BLOCK_SMS", "type": "STRING"},
        {"name": "BRANCH", "type": "STRING"},
        {"name": "CITY", "type": "STRING"},
        {"name": "COUNTRY", "type": "STRING"},
        {"name": "CREATE_DATE", "type": "TIMESTAMP"},
        {"name": "DATE_LAST_MODIFIED", "type": "TIMESTAMP"},
        {"name": "DATE_OF_BIRTH", "type": "TIMESTAMP"},
        {"name": "DATE_UPDATED", "type": "TIMESTAMP"},
        {"name": "DEFAULT_AP_ACCOUNT_ID", "type": "INTEGER"},
        {"name": "DELIVERY_PERSON", "type": "STRING"},
        {"name": "DIC", "type": "STRING"},
        {"name": "EMAIL", "type": "STRING"},
        {"name": "EMPLOYEE_RECORD_REFERENCE_ID", "type": "INTEGER"},
        {"name": "ENTITY_CODE", "type": "STRING"},
        {"name": "ENTITY_EXTID", "type": "STRING"},
        {"name": "ENTITY_ID", "type": "INTEGER"},
        {"name": "ENTITY_TYPE", "type": "STRING"},
        {"name": "EXPIRATION_DATE_FOR_LOYALTY_S", "type": "TIMESTAMP"},
        {"name": "FIRST_NAME", "type": "STRING"},
        {"name": "FROM_CAMPAIGN", "type": "STRING"},
        {"name": "FROM_LANDING", "type": "STRING"},
        {"name": "FULL_NAME", "type": "STRING"},
        {"name": "GLOBAL_SUBSCRIPTION_STATUS", "type": "INTEGER"},
        {"name": "ICO", "type": "STRING"},
        {"name": "IDENTITY_NO_", "type": "STRING"},
        {"name": "IDENTITY_PROVIDED_AGENCY", "type": "STRING"},
        {"name": "IDENTITY_PROVIDED_DATE", "type": "TIMESTAMP"},
        {"name": "ISRELEASEDCOACHING", "type": "STRING"},
        {"name": "IS_INACTIVE", "type": "STRING"},
        {"name": "IS_LEAD__BN_BUN", "type": "STRING"},
        {"name": "IS_ONLINE_BILL_PAY", "type": "STRING"},
        {"name": "IS_UNAVAILABLE", "type": "STRING"},
        {"name": "LAST_MODIFIED_DATE", "type": "TIMESTAMP"},
        {"name": "LAST_NAME", "type": "STRING"},
        {"name": "LAST_SALES_ACTIVITY", "type": "TIMESTAMP"},
        {"name": "LOGIN_ACCESS", "type": "STRING"},
        {"name": "LOYALTY_ELIGIBILITY", "type": "STRING"},
        {"name": "LOYALTY_GROUP_ID", "type": "INTEGER"},
        {"name": "LOYALTY_GROUP_LEVEL", "type": "INTEGER"},
        {"name": "LOYALTY_REMAINING_POINT_VALUE", "type": "INTEGER"},
        {"name": "LOYALTY_SMS_VALUE_PENDING_UPD", "type": "STRING"},
        {"name": "LSA_LINK", "type": "STRING"},
        {"name": "LSA_LINK_NAME", "type": "STRING"},
        {"name": "MIDDLE_NAME", "type": "STRING"},
        {"name": "NAME", "type": "STRING"},
        {"name": "NEW_SEGMENT_ID", "type": "INTEGER"},
        {"name": "NGY_TO_LEAD", "type": "TIMESTAMP"},
        {"name": "NOTES", "type": "STRING"},
        {"name": "N__GI_RATING_ID", "type": "INTEGER"},
        {"name": "ONBOARDING_DATE", "type": "TIMESTAMP"},
        {"name": "ORIGINATOR_ID", "type": "STRING"},
        {"name": "PARENT_ID", "type": "INTEGER"},
        {"name": "PARTNER_RECORD_REFERENCE_ID", "type": "INTEGER"},
        {"name": "PERMISSION_CHECK_PRINT", "type": "STRING"},
        {"name": "PHONE", "type": "STRING"},
        {"name": "RELEASE_REASON_ID", "type": "INTEGER"},
        {"name": "SALES_REP_JOB_TITLE_ID", "type": "INTEGER"},
        {"name": "SALUTATION", "type": "STRING"},
        {"name": "SMS_FOR_EXP_DATE", "type": "TIMESTAMP"},
        {"name": "SMS_PROMO_ID", "type": "STRING"},
        {"name": "SMS_SENT_DATE", "type": "TIMESTAMP"},
        {"name": "SOURCES_ID", "type": "INTEGER"},
        {"name": "SPECIAL_DISCOUNT", "type": "INTEGER"},
        {"name": "STATE", "type": "STRING"},
        {"name": "SUBSIDIARY", "type": "INTEGER"},
        {"name": "TAX_CONTACT_FIRST_NAME", "type": "STRING"},
        {"name": "TAX_CONTACT_ID", "type": "INTEGER"},
        {"name": "TAX_CONTACT_LAST_NAME", "type": "STRING"},
        {"name": "TAX_CONTACT_MIDDLE_NAME", "type": "STRING"},
        {"name": "UNSUBSCRIBED", "type": "STRING"},
        {"name": "UPDATE_TIMESTAMP", "type": "TIMESTAMP"},
        {"name": "VAT_REGISTRATION_NO", "type": "STRING"},
        {"name": "VN_CODE", "type": "STRING"},
        {"name": "ZIPCODE", "type": "STRING"},
    ]
    columns = [
        Column("ACCOUNT_OWNER_NAME", String),
        Column("ADDRESS_ONE", String),
        Column("ADDRESS_THREE", String),
        Column("ADDRESS_TWO", String),
        Column("APPROVE_PERSON", String),
        Column("BANKS_BRANCH", String),
        Column("BANK_ACCOUNT", String),
        Column("BANK_NAME", String),
        Column("BLOCK_SMS", String),
        Column("BRANCH", String),
        Column("CITY", String),
        Column("COUNTRY", String),
        Column("CREATE_DATE", DateTime(timezone=True)),
        Column("DATE_LAST_MODIFIED", DateTime(timezone=True)),
        Column("DATE_OF_BIRTH", DateTime(timezone=True)),
        Column("DATE_UPDATED", DateTime(timezone=True)),
        Column("DEFAULT_AP_ACCOUNT_ID", Integer),
        Column("DELIVERY_PERSON", String),
        Column("DIC", String),
        Column("EMAIL", String),
        Column("EMPLOYEE_RECORD_REFERENCE_ID", Integer),
        Column("ENTITY_CODE", String),
        Column("ENTITY_EXTID", String),
        Column("ENTITY_ID", Integer),
        Column("ENTITY_TYPE", String),
        Column("EXPIRATION_DATE_FOR_LOYALTY_S", DateTime(timezone=True)),
        Column("FIRST_NAME", String),
        Column("FROM_CAMPAIGN", String),
        Column("FROM_LANDING", String),
        Column("FULL_NAME", String),
        Column("GLOBAL_SUBSCRIPTION_STATUS", Integer),
        Column("ICO", String),
        Column("IDENTITY_NO_", String),
        Column("IDENTITY_PROVIDED_AGENCY", String),
        Column("IDENTITY_PROVIDED_DATE", DateTime(timezone=True)),
        Column("ISRELEASEDCOACHING", String),
        Column("IS_INACTIVE", String),
        Column("IS_LEAD__BN_BUN", String),
        Column("IS_ONLINE_BILL_PAY", String),
        Column("IS_UNAVAILABLE", String),
        Column("LAST_MODIFIED_DATE", DateTime(timezone=True)),
        Column("LAST_NAME", String),
        Column("LAST_SALES_ACTIVITY", DateTime(timezone=True)),
        Column("LOGIN_ACCESS", String),
        Column("LOYALTY_ELIGIBILITY", String),
        Column("LOYALTY_GROUP_ID", Integer),
        Column("LOYALTY_GROUP_LEVEL", Integer),
        Column("LOYALTY_REMAINING_POINT_VALUE", Integer),
        Column("LOYALTY_SMS_VALUE_PENDING_UPD", String),
        Column("LSA_LINK", String),
        Column("LSA_LINK_NAME", String),
        Column("MIDDLE_NAME", String),
        Column("NAME", String),
        Column("NEW_SEGMENT_ID", Integer),
        Column("NGY_TO_LEAD", DateTime(timezone=True)),
        Column("NOTES", String),
        Column("N__GI_RATING_ID", Integer),
        Column("ONBOARDING_DATE", DateTime(timezone=True)),
        Column("ORIGINATOR_ID", String),
        Column("PARENT_ID", Integer),
        Column("PARTNER_RECORD_REFERENCE_ID", Integer),
        Column("PERMISSION_CHECK_PRINT", String),
        Column("PHONE", String),
        Column("RELEASE_REASON_ID", Integer),
        Column("SALES_REP_JOB_TITLE_ID", Integer),
        Column("SALUTATION", String),
        Column("SMS_FOR_EXP_DATE", DateTime(timezone=True)),
        Column("SMS_PROMO_ID", String),
        Column("SMS_SENT_DATE", DateTime(timezone=True)),
        Column("SOURCES_ID", Integer),
        Column("SPECIAL_DISCOUNT", Integer),
        Column("STATE", String),
        Column("SUBSIDIARY", Integer),
        Column("TAX_CONTACT_FIRST_NAME", String),
        Column("TAX_CONTACT_ID", Integer),
        Column("TAX_CONTACT_LAST_NAME", String),
        Column("TAX_CONTACT_MIDDLE_NAME", String),
        Column("UNSUBSCRIBED", String),
        Column("UPDATE_TIMESTAMP", DateTime(timezone=True)),
        Column("VAT_REGISTRATION_NO", String),
        Column("VN_CODE", String),
        Column("ZIPCODE", String),
    ]
    connector = connector.NetSuiteConnector
    getter = getter.TimeIncrementalGetter
    loader = [
        # loader.PostgresStandardLoader,
        loader.BigQueryIncrementalLoader,
    ]
